### ISSUE TITLE
[BUG] placeholder attribute of a BoltForms not possible to translate.

### ISSUE THREAD

**Issue by nestordedios** [AnimalDesign/bolt-translate#106]
Hi again @SahAssar ,

I'm using Translate extension and next to it taking the advantage of the nice feature to translate BoltForms with `{% form_theme form '@bolt/frontend/boltforms_theme_translated.twig' %}`. As the Docs explain... I'm using Labels extension as well.

Details
-------

 - Translate Version: [ dev-master ]
 - Labels Version: [ 3.0.4 ]
 - BoltForms Version: [ dev-master ] 
 - Install type: [ Extension Repositoryl ]
 - Bolt Version: [ 3.2.5  ]
 - PHP version: [ 5.6 ]
 - Used webserver: [ Apache/2.2.22 (Debian) ]

Reproduction
------------

I have created a form with the following fields:
```
fields:
    profile_type:
      type: choice
      options:
        label: ' '
        choices: { 'User': 'user', 'Admin': 'admin' }
    email:
      type: email
      options:
        attr:
            placeholder: 'Enter your Email'
        label: 'Email '
    user_id:
      type: text
      options:
        attr:
            placeholder: 'Enter your ID number'
        label: 'ID number '
    send:
      type: submit
      options:
        attr:
          class: button
```

When I render the form `{{ boltforms('nameOfTheForm') }}` the `choices` of the `choice` field and the value of the `label` option are inserted in the Labels extension table but not the value of the `placeholder` option.

The final result I'm looking for is:
 
![form](https://cloud.githubusercontent.com/assets/6607455/22830129/ad61551e-efa5-11e6-9a2f-c145eb53fd97.PNG)

where the `placeholder` of the `<input>` can be translated using Labels extension as well. 

Is this already possible to achieve and I'm missing something or it is not implemented?

Regards!!
