### ISSUE TITLE
Can't edit English content

### ISSUE THREAD

**Issue by fojtcz** [AnimalDesign/bolt-translate#28]
Hi,

my default language in Bolt is Czech, I can create new entries with no problem. Everything is saved in database. But if I go to list of entries and try to open my English entry. I see only Czech texts.

Sorry for my English,
Martin

**Comment by SahAssar** [comment]
Hey @fojtcz,

So, both the default language (first in locales) and your bolt backend language is Czech, right? Is this on bolt 2.2 or 3.0?  Also, can you check in your browsers dev tools if you have any errors there?

**Comment by fojtcz** [comment]
Hi @SahAssar,

yeah, i set my default language to Czech. I am using latest Bolt 3.0. I don't see any errors in dev tools.

**Comment by SahAssar** [comment]
@fojtcz could you post your contenttypes.yml, your extension config (translate.animal.yml) and your config.yml so that I can reproduce the issue?

Thanks!

**Comment by SahAssar** [comment]
@fojtcz Oh, wait, you're using the latest stable 3.0? Cause this will only work in the dev version of bolt 3.0 until 3.0.10 is released...

**Comment by fojtcz** [comment]
@SahAssar yes, i am using stable version of Bolt 3.0.9.

my `translate.animal.yml`

```
locales:
    cs_CZ:
        label: Čeština
        slug: cs
    en_GB:
        label: English
        slug: en

routing_override: false
menu_override: false
translate_slugs: false
```
