### ISSUE TITLE
Translatable fields are not showing: dev-master (6d1a7d)

### ISSUE THREAD

**Issue by peterboorsma** [AnimalDesign/bolt-translate#29]
After installing and adding the correct additions to contenttypes.yml, config and updating the database.
Two issues:

1. Existing items now have a Language tab. The tab dropdown items have links like this: http://bla.localhost/bolt/editcontent/paginas/1?_locale=en
but the toggle to the translatable fields don't work. (page reloads instead of showing the right fields)

2. New items don't show the language tab at all.

In both cases the translate icons for translatable filetypes are missing.

**Comment by madc** [comment]
Do you get any Javascript errors in the console?

**Comment by peterboorsma** [comment]
Yes. 

```
lib.js?2ed94ca141:24 Uncaught Error: Syntax error, unrecognized expression: http://stortemelk3.localhost/beheer/editcontent/paginas/1?_locale=enb.error @ lib.js?2ed94ca141:24b.tokenize @ lib.js?2ed94ca141:24b.select @ lib.js?2ed94ca141:24b @ lib.js?2ed94ca141:24find @ lib.js?2ed94ca141:24fa.fn.init @ lib.js?2ed94ca141:24fa @ lib.js?2ed94ca141:14c.show @ lib.js?2ed94ca141:90(anonymous function) @ lib.js?2ed94ca141:90each @ lib.js?2ed94ca141:14each @ lib.js?2ed94ca141:14b @ lib.js?2ed94ca141:90(anonymous function) @ bolt.js?4c21e560ba:8dispatch @ lib.js?2ed94ca141:25q.handle @ lib.js?2ed94ca141:24
Navigated to http://stortemelk3.localhost/beheer/editcontent/paginas/1?_locale=en
```

**Comment by SahAssar** [comment]
1. That's intentional for now. Until you have saved it it does not have anywhere to "save" the translations, (I'll try to work around this in the future to allow records to only be in an non-default locale).

2. The behavior is changed from setting the items via JS to setting them on the backend via the _locale query string. This is done so that we don't have to write specific js code to load fields (both bolt's own and extension fields) and also because the JS we wrote to load/unload fields was probably the most fragile thing about the 2.0 version simply because it was often fighting with bolt's own JS and the way that bolt's ajax save cycle worked.

Sounds to me like it's working as it should and the lib.js sounds like it might be unrelated since it is not from this extension.

**Comment by peterboorsma** [comment]
```
paginas:
    name: Paginas
    singular_name: Pagina
    fields:
        locale:
            type: locale
            group: Tekst
        title:
            type: text
            class: large
            label: Titel
            group: Tekst
            isTranslatable: true
        slug:
            type: slug
            uses: title
            group: Tekst
        quote:
            type: text
            class: large
            variant: inline
            label: Quote header
            postfix: '<p>Wordt over de headerafbeelding getoond</p>'
            group: Tekst
            isTranslatable: true
        teaser:
            type: html
            height: 150px
            label: Korte introductietekst
            group: Tekst
            isTranslatable: true
        body:
            type: html
            height: 300px
            label: Uitgebreide tekst
            group: Tekst
            isTranslatable: true
        image:
            type: image
            label: Afbeelding header (1000 x 400 pixels. Fotomateriaal altijd jpg maken.)
            group: Media
        credit:
            type: text
            class: narrow
            label: Naam fotograaf
            variant: inline
            postfix: '<hr>'
            group: Media
        selectslideshow:
            type: select
            values: slideshows/title
            label: Selecteer een slideshow voor bovenaan deze pagina
            group: Media
            postfix: '<hr>'
        selectblokje:
            type: select
            values: actieblokjes/title
            label: Selecteer een actieblokje dat op deze pagina getoond wordt
            postfix: '<hr>'
        selectdownload:
            type: select
            values: downloads/title
            multiple: true
            sort: title
            label: Selecteer een of meer downloads die op deze pagina getoond worden
            postfix: '<hr>'
        seo:
            type: seo
            group: SEO
    taxonomy: [ hoofdstukken, tags ]
    record_template: item_pagina.twig
    listing_template: listing.twig
    recordsperpage: 100
    listing_records: 100
```

**Comment by SahAssar** [comment]
@peterboorsma The issue here is just that while fixing a few other things I changed isTranslateable to is_translateable since it better follows bolt's and YAML's rules about key names that way (I thought it was best to fix all the things that has bothered me in one breaking change when I have to bump major versions anyway).

Just change isTranslateable to is_translateable and it should work :)

**Comment by peterboorsma** [comment]
Yes. I used the old "isTranslatable". Updated them now.

But...
(and I am sorry) the translations aren't stored properly. If you toggle back and forth between the languages the translated fields are not saved.
Is it intentional that the page is refreshed in the browser instead of changing the translatable fields 'ajaxy'? Because that's what's happening.

**Comment by SahAssar** [comment]
@peterboorsma yeah, it's intentional to refresh the browser instead of doing it ajaxy... That way it will be much more compatible and robust. The old way of doing it ajaxy would be much harder to make compatible with extensions and would require us to write js for loading values into every extension fieldtype.

For me (when testing with your contenttype) it seems like DB query result is getting cached... Could you try updating page with translations a few times and see if your translations appear then? Perhaps local extensions do not get their DB queries results cached which would explain why I didn't see this when writing the code...

**Comment by SahAssar** [comment]
@peterboorsma Or you should be able to disable the cache by adding `database: false` to the caching config in config.yml so it looks like this:

```
caching:
    config: true
    templates: true
    request: false
    duration: 10
    authenticated: false
    thumbnails: true
    database: false
```
