### ISSUE TITLE
[BUG] Doesn't save data on repeater fields

### ISSUE THREAD

**Issue by zomars** [AnimalDesign/bolt-translate#31]
I got a website that use repeater fields a lot. I tried to configure my `contenttypes.yml` like this:

```yaml
repeater:
	type: repeater
	is_translateable: true
	fields:
		repeattitle:
			type: text
			is_translateable: true
```

Maybe I'ts not supported but I couldn't find anything in the docs.

Thanks for keeping this plugin so great, cheer mate!

**Comment by madc** [comment]
I think, that repeaters are not yet implemented, see [#24](https://github.com/AnimalDesign/bolt-translate/issues/24#issuecomment-232145559)

**Comment by zomars** [comment]
I see, still this counts as a bug right? I wasn't aware it was mentioned there.

**Comment by SahAssar** [comment]
@zomars They should be implemented on the backend, but not on the frontend due to bolt/bolt/issues/5533. Do they not work on the backend for you?

**Comment by zomars** [comment]
I think the reason it wasn't working in the backend was because of #32. I'll update and test it again.

**Comment by SahAssar** [comment]
As of bdac3fa repeaters should work both in front and back end, @zomars could you check if the issue is solved for you? Perhaps I can then tag a release of the ext :)

**Comment by zomars** [comment]
Backend is working fine, but somehow translated repeaters are not rendering at all in the front, only the default locale.

**Comment by zomars** [comment]
Some additional info:
```yaml
repeater:
    type: repeater
    group: repeater
    is_translateable: true
    fields:
        repeattitle:
            type: text
        repeatcontent:
            type: html
        repeatimage:
            type: image
            extensions: [ gif, jpg, png ]
        repeatlink:
            type: text
        repeatbgcolor:
            type: select
            values: [ "white", "light-gray" ]
```
Also my current theme is css only modified version of the current `base-2016` theme
