### ISSUE TITLE
Any suggestions to creating a translated menu?

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#6]
menu{locale}.yml or would you 
```
main:
    - label: home/{locale}
      title: This is the first menu item.
      path: homepage
      class: first
[etc...]
```

p.s.: Sorry for skipping on the SEO. I'm still working on it.

*edit:
nvm. Found the answer: removing the title property from the menu will replace it with the slug for the set language.
