### ISSUE TITLE
[BUG] Page page/ not found

### ISSUE THREAD

**Issue by frozenshadow** [AnimalDesign/bolt-translate#70]
I posted this issue earlier right before the 3.1.2 release, and hoped it was fixed in that release. But the problem remains.

I have done multiple clean installs (Bolt 3.0.12 & 3.1.0 beta 2), and all single page views got 404 errors after installing translate. Also upgraded one install from 2.2.23 to 3.0.12 and got an fatal error (because there wasn't a 404 page in the theme):

```
Request URL: bolt.prod/nl/page/over-ons
Symfony\Component\HttpKernel\Exception\HttpException thrown with message "Page page/ not found."

Stacktrace:
#9 Symfony\Component\HttpKernel\Exception\HttpException in /home/vagrant/projects/bolt-prod/vendor/silex/silex/src/Silex/Application.php:400
#8 Silex\Application:abort in /home/vagrant/projects/bolt-prod/vendor/bolt/bolt/src/Controller/Base.php:62
#7 Bolt\Controller\Base:abort in /home/vagrant/projects/bolt-prod/vendor/bolt/bolt/src/Controller/Frontend.php:155
#6 Bolt\Controller\Frontend:record in /home/vagrant/projects/bolt-prod/extensions/vendor/animal/translate/src/Frontend/LocalizedFrontend.php:78
#5 Bolt\Extension\Animal\Translate\Frontend\LocalizedFrontend:record in /home/vagrant/projects/bolt-prod/vendor/symfony/http-kernel/HttpKernel.php:144
#4 call_user_func_array in /home/vagrant/projects/bolt-prod/vendor/symfony/http-kernel/HttpKernel.php:144
#3 Symfony\Component\HttpKernel\HttpKernel:handleRaw in /home/vagrant/projects/bolt-prod/vendor/symfony/http-kernel/HttpKernel.php:64
#2 Symfony\Component\HttpKernel\HttpKernel:handle in /home/vagrant/projects/bolt-prod/vendor/silex/silex/src/Silex/Application.php:586
#1 Silex\Application:handle in /home/vagrant/projects/bolt-prod/vendor/silex/silex/src/Silex/Application.php:563
#0 Silex\Application:run in /home/vagrant/projects/bolt-prod/public/index.php:14
```

Details
-------

 - Translate Version: all 3.x.x releases
 - Install type: Extension Repository and Local install
 - Bolt Version: 3.0.12 and 3.1.0 beta 2
 - PHP version: 7.0
 - Used webserver: Nginx version 1.9.11 (homestead 0.5.0)

I hope this is enough info. If you need a full reproduction log, please let me know :wink:

**Comment by madc** [comment]
Could you also post your setup from `translate.animal.yml` and the `pages` contenttype?

**Comment by frozenshadow** [comment]
Sure, here you go.

Contenttype:
```YAML
pages:
    name: Pages
    singular_name: Page
    fields:
        locale:
            type: locale
            group: content
        title:
            type: text
            class: large
            group: content
            isTranslatable: true
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
            isTranslatable: true
        body:
            type: html
            height: 300px
            isTranslatable: true
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ groups ]
    recordsperpage: 100
```

translate.animal.yml:
```YAML
# The locales the site should be available in
locales:
    nl_NL:
        label: Nederlands
        slug: nl
    en_GB:
        label: Engels
        slug: en
    es_ES:
        label: Spaans
        slug: es

# Enable/disable automatic routing override.
# Enabling this will prefix all routes with {_locale} which leads to links like
# /en/pages/yourpageslug It is recommended that you leave this on unless you
# want to build your own routing.
routing_override: true

# Enable/disable the menubuilder override.
# Enabling this will make the menu output links in the format of the automatic
# routing. It is recommended that you leave this on unless you want to build
# your own localized menus.
menu_override: true

# Enable/disable the url_generator override.
# Enabling this will override the url generator to make sure that we don't
# generate links without a locale. This is highlig recommended to keep unless
# you also build your own override since it can cause WSOD on 404's otherwise.
url_generator_override: true

# Enable/disable translated slugs.
# Enabling this will use translated slugs instead of using the same slug for
# all languages. Only set to false if you also don't set your slugs to `is_translateable`. 
translate_slugs: true

# Enable/disable using Accept-Language header to determine the locale for
# redirection on `/`.
# Enabling this will redirect visitors on `/` to the preferred locale based on
# the Accept-Language header. Disabling this will always redirect `/` to the
# first locale set in `locales` above.
use_accept_language_header: true
```
