### ISSUE TITLE
[BUG] exension doesn't save secondary locale

### ISSUE THREAD

**Issue by danielschleindlsperger** [AnimalDesign/bolt-translate#72]
Hello,

when I try to save a contenttype with a repeater it only saves for the primary locale, not the secondary. The secondary locale is always the same as the primary.

#### translate config:
```yaml
locales:
    de_DE:
        label: Deutsch
        slug: de
    en_GB:
        label: English
        slug: en
```

#### contenttype:
```yaml
staffgroup:
    name: Staff Groups
    singular_name: Staff Group
    fields:
        locale:
            type: locale
            group: content
        title:
            type: text
            label: Title
            is_translateable: true
        people:
            type: repeater
            label: People in Group
            is_translateable: true
            fields:
                image:
                    type: image
                    label: Image
                name:
                    type: text
                    label: Name
                role:
                    type: text
                    label: Role in company
                info:
                    type: html
                    height: 150px
                    label: More info about person
    show_on_dashboard: true
    viewless: true
    default_status: publish
    searchable: false
    icon_many: "fa:users"
    icon_one: "fa:user"
```

Also I get the following js error in the browser console:
```js
lib.js?b5478a6a75:24 Uncaught Error: Syntax error, unrecognized expression: http://domain-redacted.dev/bolt/editcontent/staffgroup/1?_locale=en
```

 - Translate Version: 3.1.2
 - Install type: Extension Repository
 - Bolt Version: 3.1
 - PHP version: 7.0

Thank you so much for you work on bolt and the translate plugin and let me know if you need more info :)
