### ISSUE TITLE
Latest version doesn't translate after following docs

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#73]
I have a bolt 3.x setup with boltforms and bolt translate. Both up to date.

```
locales:
    nl_NL:
        label: Nederlands
        slug: nl
    en_GB:
        label: English
        slug: en
    de_AT:
        label: Deutsch
        slug: de
```

That's my change on the translate yml config (644)

After prompted and confirmed on db update. The tabs do not seem to work.

Even after adding isTranslatable: true to the ct.yml fields content is still not translated.

*edit: Oops, seems isTranslatable changed to is_translateable I should not have lived under a rock for this long!
