### ISSUE TITLE
page setup

### ISSUE THREAD

**Issue by Puddingboy** [AnimalDesign/bolt-translate#8]
This is a bit complex to explain, but I hope you'll bear with me. What happens is. I first have to save a new page before I can add languages. This is not bad. However, after I've saved the page the main language inherits from this saved page. This is not the issue I want you to fix, I would like you to look into the following:

Can you also make it so that the main page also inherits from the main language rather than only the other way around?

What it's currently like:

```
parent:{title},{body},etc
  - {main language}{title},{body},etc > inherits from parent
  - {language 2}{title},{body},etc
  - {language 2}{title},{body},etc
```
What I would like:
```
parent:{title},{body},etc < inherit from main language
  - {main language}{title},{body},etc > inherits from parent
  - {language 2}{title},{body},etc
  - {language 2}{title},{body},etc
```

**Comment by SahAssar** [comment]
@Puddingboy Is your backend language (the `locale` setting in config.yml) set as the same as the first locale in the `locales` setting? cause if it is it should work pretty much as detailed, I'm working on a update to make this more obvious/ fix it permanently.

**Comment by Puddingboy** [comment]
```
locales:
    nl_NL:
        label: Nederlands
        slug: nl
    fr_FR:
        label: Français
        slug: fr
    en_EN:
        label: English
        slug: en
```
This is my locale setting, in which Dutch is my main language.

What happens is that someone can click on a page in the pages menu and they are redirected to some kind of parentpage. Somehow parentpage and mainlanguage are not in sync.
