### ISSUE TITLE
[BUG] Cannot save contenttype

### ISSUE THREAD

**Issue by frozenshadow** [AnimalDesign/bolt-translate#81]
When saving a contenttype the following error appears:

```
Could not save [contenttype].
The given alias '[contenttype]' is not unique in FROM and JOIN clause table. The currently registered aliases are: [contenttype].
```

**Note:** this is only when saving a translation other than the Bolt default language.
## Details
- Translate Version: 4.0.0
- Install type: Extension Repository
- Bolt Version: 3.1.4 (fresh and upgraded from 2.2)
- PHP version: 7.0.3
- Used webserver: Nginx version 1.9.11

**Comment by frozenshadow** [comment]
After some testing with @SahAssar it appears to be the relation defined in the contenttype. And only when the relation is pointing to itself, like this:

```YML
demos:
    name: Demos
    slug: demos
    singular_name: Demo
    singular_slug: demo
    fields:
        locale:
            type: locale
            group: Text
        title:
            type: text
            class: large
            required: true
            pattern: ".{2,255}" # see: http://html5pattern.com/
            error: "The Title field is required, and must contain at least 2 characters"
            group: Text
            is_translateable: true
        slug:
            type: slug
            uses: [ title ]
        endata:
            type: hidden
        enslug:
            type: locale_data
            index: true
        dedata:
            type: hidden
        deslug:
            type: locale_data
            index: true
    relations:
        demos:
            multiple: true
            label: "Choose an entry"
            order: -id
            format: "{{ item.title|escape }} <span>(№ {{ item.id }})</span>"
            postfix: "By selecting an Entry, you're creating a bi-directional relationship to that Entry."
    taxonomy: [ categories, tags ]
    show_on_dashboard: true
    default_status: publish
    searchable: true
    icon_many: "fa:gift"
    icon_one: "fa:gift"
```
