### ISSUE TITLE
[BUG] Version 4 does not seem to respect default lang

### ISSUE THREAD

**Issue by sbonardt** [AnimalDesign/bolt-translate#87]
I've updated my (working) Translate extension from 3.1 on a Bolt 3 to the latest version 4 (with latest Bolt) but it doesn't seem to recognise the default language set in the Bolt main config file anymore.

I've set the Bolt main locale in config to: nl_NL

In the extension config (translate.animal.yml) I've set:

```
# The locales the site should be available in
locales:
    nl_Nl:
        label: NL
        slug: nl
    en_GB:
        label: EN
        slug: en
```

And thus made sure the default is the first one in order. (nl_NL)

And in contenttypes.yml i've set the required locale fields in the contenttypes:

```
        locale:
            type: locale
            group: main
        nldata:
            type: hidden
        nlslug:
            type: locale_data
            index: true
        endata:
            type: hidden        
        enslug:
            type: locale_data
            index: true
```

When I load the homepage the default go to language is however en_GB and not nl_NL as expected. Also in the backend '?_locale=en' keeps getting added as default lang.
I expect to see the default language nl_NL loaded in frontend as well as backend.

It looks like I've set all required settings and config. (?)

Tested with Bolt 3.1.5 and Translate versions 4.0.1 and 4.0.0. Going back to versions 3.x.x doesn't work with Bolt 3.1.5
