### ISSUE TITLE
[BUG] Maximum execution time exceeded

### ISSUE THREAD

**Issue by RickvanB** [AnimalDesign/bolt-translate#97]
Hello,

I installed the plugin on my shared hosting, because openssl doens't work locally. The homepage works fine, but whenever I'm trying to visit another page on my website. It get's in an endless loop and after that I get the message from Bolt that my maximum execution time is exceeded.

Details:
- Latest version of Translate
- Installed via Bolt CMS
- Bolt version 3.2.3
- PHP version 5.6
- Webserver: Apache

Translate config:
```
# The locales the site should be available in
locales:
    nl_NL:
        label: Nederlands
        slug: nl
    en_GB:
        label: Engels
        slug: en

routing_override: true
menu_override: true
url_generator_override: true
translate_slugs: true
use_accept_language_header: true
```
I think it has something todo with the routing, but I'm not an expert in Bolt..
Anybody had this problem before and can help me?

Thanks in advance.

**Comment by SahAssar** [comment]
Hmm, I've never seen it go looping off like that, Could you perhaps check the debug profiler so see if that gives us any more info?

**Comment by RickvanB** [comment]
Hi, thanks for answering! Where can I find that.
This is the url: https://test.inchplastics.nl/nl/pagina/over-ons. So you can check by yourself if necessary.

**Comment by SahAssar** [comment]
Hmm, it looks like it's hitting that execution time in monolog, but the only place we use the logger is in the menu, here: https://github.com/AnimalDesign/bolt-translate/search?utf8=%E2%9C%93&q=logger, so I'm guessing it's something to do with the menu. Could you post your menu.yml? Also, the debugger can be turned on and off in the main config.yml and is then shown on the bottom of every page.

**Comment by RickvanB** [comment]
Debug is turned on in the main config.yml, but for some reason it doens't show up when the error is thrown.

My menu.twig (the most important, the rest is just html):
          ```
<nav id="site-navigation" class="clearfix" role="navigation">
            {% setcontent pages = 'pages/latest/6' orderby 'id'  %}
            <div class="menu-container">
              {% for page in pages %}
                {% if loop.first %}<ul id="menu-main-menu" class="menu">{% endif %}
                <li class="menu-item {% if page|current %}current-menu-item{% endif %}"><a href="{{ page.link }}">{{ page.title|trimtext(12) }}</a></li>
                {% if loop.last %}</ul>{% endif %}
              {% endfor %}
            </div>
          </nav>
```

As I see now, my menu.yml is never changed (just default stuff), maybe that's the problem?
```
main:
    - label: Home
      title: This is the first menu item.
      path: homepage
      class: first
    - label: Second item
      path: entry/1
      submenu:
          - label: Sub 1
            path: entry/2
          - label: Sub 2
            class: menu-item-class
            path: entry/3
          - label: Sub 3
            path: entry/4
          - label: Sub 4
            class: sub-class
            path: page/3
    - label: All pages
      path: pages/
    - label: The Bolt site
      link: http://bolt.cm
      class: last
```
