### ISSUE TITLE
[BUG] Back-end gets stuck when saving a translated html field

### ISSUE THREAD

**Issue by zomars** [AnimalDesign/bolt-translate#99]
I've made some tests, and it only happens when trying to save an html field in another language. I get this: 

```
FatalErrorException in AbstractProcessingHandler.php line 29:
Error: Maximum execution time of 30 seconds exceeded
```

My contenttypes.yml

```yaml
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
            is_translateable: true
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
            is_translateable: true
        body:
            type: html
            height: 300px
            is_translateable: true
        locale:
            type: locale
            group: content
        esdata:
            type: hidden
        esslug:
            type: locale_data
            index: true
        endata:
            type: hidden
        enslug:
            type: locale_data
            index: true
```

translage.animal.yml

```yaml
locales:
    es_ES:
        label: Español
        slug: es
    en_GB:
        label: English
        slug: en
routing_override: false
menu_override: true
url_generator_override: true
translate_slugs: true
use_accept_language_header: true
```

Details
-------

 - Translate Version: 4.0.1
 - Install type: Extension Repository
 - Bolt Version: 3.2.6
 - PHP version: 7.1
 - Used webserver: Apache version 2.4
